services:
  cve:
    build: .
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:7.16.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"
