services:
  cve:
    build: ..
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  kibana:
    image: kibana:7.16.2
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
