services:
  cve:
    build: ..
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      kibana:
        condition: service_healthy
  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  kibana:
    image: kibana:8.4.1
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    healthcheck:
      test: curl --fail http://localhost:5601/api/status || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
